name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # Run manually
  workflow_dispatch:
  # Run on new main update
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alexcosta97
          base: ''
          config_timezone: Europe/London
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_sections: recently-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_recent_load: 10000
          plugin_languages_recent_days: 30
          plugin_languages_other: no
          plugin_achievements: yes
          plugin_achievements_limit: 10
          optimize: svg
          experimental_features: --optimize-svg
